### ISSUE TITLE
Update installer to install Hugo 0.18.1

### ISSUE THREAD

**Issue by ryanewtaylor** [switchspan/chocolatey-hugo#5]
Hugo 0.18.1 is now available. Can this installer be updated to install Hugo 0.18.1?

**Comment by ryanewtaylor** [comment]
PR #6 should address this request, if you find it suitable.

FWIW, I edited the files on Windows. In the .\tools\chocolatelyInstall.ps1 files a git diff showed that my modifications introduced a ^M at the end of the modified lines. However, I do not see these in the PR so this may be okay.

**Comment by switchspan** [comment]
Closing this out as the current package is updated to v0.19
